### ISSUE TITLE
Export as json fails

### ISSUE THREAD

**Issue by fvarrui** [teuton-software/teuton#21]
When I run the next command:
```bash
teuton play <challenge-folder> --export=json
```
I've got the next error:

```
C:/Program Files/teuton/lib/formatter/yaml_formatter.rb:58:in `build_history_data': undefined local variable or method `bady' for #<JSONFormatter:0x0000000005f17a20> (NameError)
Did you mean?  body
	from C:/Program Files/teuton/lib/formatter/yaml_formatter.rb:20:in `build_data'
	from C:/Program Files/teuton/lib/formatter/json_formatter.rb:13:in `process'
	from C:/Program Files/teuton/lib/report.rb:34:in `export'
	from C:/Program Files/teuton/lib/case_manager/export.rb:13:in `export'
	from C:/Program Files/teuton/lib/case_manager.rb:44:in `play'
	from C:/Program Files/teuton/lib/case_manager/dsl.rb:11:in `play'
	from D:/Users/fvarrui/Documents/GitHub/teuton-challenges/os-basic-level/users_and_groups/start.rb:40:in `<top (required)>'
	from C:/Program Files/teuton/lib/project.rb:38:in `require_relative'
	from C:/Program Files/teuton/lib/project.rb:38:in `play'
	from C:/Program Files/teuton/lib/command/play.rb:25:in `play'
	from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from C:/Program Files/teuton//teuton:32:in `<main>'
```

**Comment by dvarrui** [comment]
Resolved!
